version: '3.8'

services:
  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      # SQLite database - file stored in mounted volume
      - DATABASE_PATH=/app/data/reencodarr_prod.db
      - SECRET_KEY_BASE=your-secret-key-base-here-change-this-in-production
      - PHX_SERVER=true
      - PORT=4000
    volumes:
      - ./media:/app/media  # Mount for media files processing
      - ./data:/app/data    # SQLite database storage
    restart: unless-stopped

volumes:
  # No database service needed - SQLite is embedded
