import Config

# Configure your database
config :reencodarr, Reencodarr.Repo,
  # username: "postgres",
  # password: "postgres",
  # hostname: "localhost",
  database: "reencodarr_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 50

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :reencodarr, ReencodarrWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  # http: [ip: {127, 0, 0, 1}, port: 4000],
  http: [ip: {0, 0, 0, 0}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "o8+a4wToO21WFs3Cj1SbK3uNtcrQOk4pCCtp5Wztzx6wJz+1GdMyyHU9Bs3BoatC",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:reencodarr, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:reencodarr, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :reencodarr, ReencodarrWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/reencodarr_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :reencodarr, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"
config :logger, level: :info

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include HEEx debug annotations as HTML comments in rendered markup
  debug_heex_annotations: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

config :live_debugger,
  # IP on which LiveDebugger will be hosted
  ip: {192, 168, 1, 5},
  # Port on which LiveDebugger will be hosted
  port: 4007,
  # Secret key used for LiveDebugger.Endpoint
  secret_key_base: "nxeC3Z+0GcRf0NKbjgCuwBQvld+KftsF+Ebsti02FZUXc6xQNR80V8Kdw5sEYiEk",
  # Signing salt used for LiveDebugger.Endpoint
  signing_salt: "QvcMLz2F3V0jO1LRee/B5207o3KoSJoMkdKP/c/V2rt4x2hxZmg7UF74uzN7QAbP",
  # Adapter used in LiveDebugger.Endpoint
  adapter: Bandit.PhoenixAdapter,
  # Forces LiveDebugger to start even if project is not started with the `mix phx.server`
  server: true,
  external_url: "http://192.168.1.5:9007"

# Load local overrides from dev.overrides.exs if exists
if File.exists?("config/dev.overrides.exs"), do: import_config("dev.overrides.exs")
